from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import NamedTuple, Protocol


class DirEntry(NamedTuple):
    name: str
    is_directory: bool
    size: int
    last_modified: str


class FileStat(NamedTuple):
    size: int
    last_modified: str | None
    etag: str | None


class Storage(Protocol):
    def write(self, key: str, content: bytes) -> None: ...
    async def write_stream(self, key: str, stream: AsyncIterator[bytes]) -> int: ...
    def read(self, key: str, byte_offset: int = 0, byte_count: int | None = None) -> bytes: ...
    def read_stream(self, key: str, chunk_size: int = 262144) -> Iterator[bytes]: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def size(self, key: str) -> int: ...
    def stat(self, key: str) -> FileStat: ...
    def list_dir(self, prefix: str) -> list[DirEntry]: ...
    def list_files(self, prefix: str) -> list[str]: ...
